server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keepmoney?serverTimezone=GMT%2b8
    #url: jdbc:mysql://114.132.54.246:3306/keepmoney?serverTimezone=GMT%2b8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

files:
  upload:
    #path: D:/图片/SpringBoot/files/
    path: /home/files/

String:
  #urls: http://localhost:9090/photo/
  urls: http://114.132.54.246:9090/photo/
